spring:
  profiles:
    active: local
  application:
    name: file-process-consumer
app:
  message-broker:
    event:
      upload:
        queue-name: upload-event-queue
      notification:
        queue-name: notification-event-queue
  storage:
    bucket: bucket-fiap-hackaton-t32-files
    pre-signed-url:
      ttl-in-hour: 24